### ISSUE TITLE
Input Text keyword name is exist in Selenium2library

### ISSUE THREAD

**Issue by Yoganathan-D** [Hi-Fi/remotesikulilibrary#20]
Input Text keyword name is already exist in Selenium2library. so better to rename this keyword with some other name in remotesikulilibrary.

**Comment by Yoganathan-D** [comment]
this keyword is creating conflict while using Selenium2library and remotesikulilibrary.

**Comment by Hi-Fi** [comment]
Duplicate keywords can be used by giving library name (or alias) with Keyword. Keyword name can be changed in library, if there's good suggestion for it. 

In technical sense "Type Text" is not very good, because text is not typed but pasted.

**Comment by Yoganathan-D** [comment]
I would suggest to make this keyword name as "Input Text In Field". already this naming format used for "Replace Text In Field" in this library.
